// Work-to-be-done catalogue - source of truth.
// Frame, fields and rules: design-kit/templates/work-to-be-done-catalogue-template.md
// Edit here, then run: node deliverables/14-work-to-be-done-catalogue.build.js
//
// Harvest status: 09: Repeat (sample, 2026-10-04). 10, 11 and 12 to follow.
// IDs are assigned by the build in data order (per type) and frozen once the full
// catalogue ships - append new items, never reorder or renumber.

const CAPS = [
  null,
  'Knowing the customer and their household',
  'Receiving and validating prescriptions',
  'Pricing, funding and payment',
  'Knowing and managing stock',
  'Dispensing and pharmacist care',
  'Collection and delivery',
  'Adherence and refills',
  'Communicating with customers',
];

const TYPES = [
  null,
  { group: 'LEARN', code: 'LRN', name: 'Research & validation' },
  { group: 'LEARN', code: 'LRN', name: 'Decisions to take' },
  { group: 'PERMIT', code: 'PRM', name: 'Regulatory reform' },
  { group: 'PERMIT', code: 'PRM', name: 'Internal policy change' },
  { group: 'BUILD', code: 'BLD', name: 'Customer-facing features' },
  { group: 'BUILD', code: 'BLD', name: 'Staff tools' },
  { group: 'BUILD', code: 'BLD', name: 'Platforms & data' },
  { group: 'BUILD', code: 'BLD', name: 'Content & standards' },
  { group: 'RUN', code: 'RUN', name: 'Processes & ways of working' },
  { group: 'RUN', code: 'RUN', name: 'People & roles' },
  { group: 'RUN', code: 'RUN', name: 'Partnerships' },
];

// Journey phase shorthands (Tier 2 "Enables")
const R = (phase) => '09: Repeat · ' + phase;
const P0 = R('Signing up'), P1 = R('Repeats are due'), P2 = R('Adding to the order'),
  P3 = R('Checked and packed'), P4 = R('In hand'), P5 = R('Taking it'), PX = R('When something breaks');

const ITEMS = [
  // ---------------------------------------------------------------- 1 Knowing the customer and their household
  { key: 'household-profile', cap: 1, type: 7, title: 'Household profile',
    need: 'One record links a household\'s members, their medicines, cover and cycles, and works the same in the app, on WhatsApp and at the counter.',
    why: 'So a carer manages four people\'s medicine as one thing, and nobody re-types what Dis-Chem already holds.',
    principles: ['Get the basics right, every time', 'Repeats should just repeat'], status: 'Planned',
    statusNote: 'HSQ: dependant profiles Planned in app and web, Gap on WhatsApp and in-store.',
    seen: ['HSQ', 'ECM', 'FUL s22'], enables: [P0, P1, P5], concepts: ['Household Medicine Cabinet'],
    deps: ['one-customer-record', 'carer-consent'], evidence: ['wiki/concepts/identity-and-consent'] },
  { key: 'one-customer-record', cap: 1, type: 7, title: 'One customer record',
    need: 'Each customer has one record, recognised in every channel and every store.',
    why: 'Profiles sit at store level today and duplicate, so people retype their details and orders lose their history.',
    principles: ['Get the basics right, every time'], status: 'Planned',
    statusNote: 'FUL s22: profiles cleaned and centralised through BRiX in the target state; MLP no change. FUL s40 lists centralised profiles as an unlock.',
    seen: ['ECM', 'FUL s22', 'FUL s40'], enables: [P0], deps: [], evidence: ['wiki/dischem/dischem-social-sentiment-trust-journey'] },
  { key: 'carer-consent', cap: 1, type: 7, title: 'Carer consent that travels',
    need: 'A recorded consent lets one person order, pay and collect for another, and every channel honours it.',
    why: 'So a carer is believed once, instead of re-proving their authority at every counter.',
    principles: ['Get the basics right, every time'], status: 'Known gap',
    statusNote: 'HSQ: proxy assignment Planned, but "acting for a dependant" is a Gap - the permission exists and does not propagate.',
    seen: ['HSQ', 'ECM', 'FUL s22'], enables: [P0, P5], concepts: ['CarerConsent'], deps: ['household-profile'],
    evidence: ['wiki/concepts/identity-and-consent'] },
  { key: 'preferences', cap: 1, type: 7, title: 'Preferences honoured everywhere',
    need: 'A customer\'s choices (channel, collection point, language per person, brand or generic, payment order) are stored once and applied to every order and message.',
    why: 'So the service runs on the customer\'s rules, not the system\'s defaults, without asking again each month.',
    principles: ['Repeats should just repeat', 'Get the basics right, every time'], status: 'Known gap',
    statusNote: 'HSQ: contact preference settings Gap; language and accessibility preference Gap.',
    seen: ['HSQ'], enables: [P0, P1, P5], deps: ['household-profile'] },
  { key: 'whatsapp-identity', cap: 1, type: 7, title: 'Verified identity on WhatsApp',
    need: 'A customer can prove who they are on WhatsApp well enough to see and manage their household\'s medicine.',
    why: 'Cash customers live on WhatsApp; without verified identity the chat can\'t show medicines or act on a carer\'s consent.',
    principles: ['Get the basics right, every time'], status: 'Known gap',
    statusNote: 'HSQ: WhatsApp has no profile ("phone number only"); in-context ID check at high-risk actions is a Gap on WhatsApp.',
    seen: ['HSQ'], enables: [P0], deps: ['one-customer-record'], evidence: ['wiki/consumer-context/digital-access-and-whatsapp'] },
  { key: 'history-suggestions', cap: 1, type: 7, title: 'Suggestions from buying history',
    need: 'The open order suggests items from the household\'s own buying history, with specials flagged.',
    why: 'So the shop that used to happen in the aisle still happens, without the customer having to remember the list.',
    principles: [], status: 'New', statusNote: 'Design assumption in 09 (punchlist item 9).',
    seen: [], enables: [P2], concepts: ['The Standing Order'], deps: ['one-customer-record'] },
  { key: 'carer-policy', cap: 1, type: 4, title: 'Carer authority policy',
    need: 'Dis-Chem defines what a carer may do for an adult, for a child and for a Schedule 6 medicine, and how the person cared for withdraws it.',
    why: 'Staff and systems need one rule to apply, so carers are neither blocked nor given more access than they should have.',
    principles: ['Get the basics right, every time'], status: 'New',
    statusNote: 'Not in any catalogue. Related HSQ Gap: sensitivity-graded consent (current model is single-tier).',
    seen: [], enables: [P0, P5], concepts: ['CarerConsent'], evidence: ['wiki/concepts/identity-and-consent'],
    question: 'Can a carer collect an adult\'s Schedule 6 medicine, and what ID check applies?' },
  { key: 'household-research', cap: 1, type: 1, title: 'Household manager research',
    need: 'Evidence on how household medicine managers want to set up and run a shared repeat service, and what would make them trust it.',
    why: 'The household model is the core of the repeat journey; we should prove carers want it before building around it.',
    principles: ['Repeats should just repeat'], status: 'New', seen: [], enables: [P0, P1] },

  // ---------------------------------------------------------------- 2 Receiving and validating prescriptions
  { key: 'repeat-rules', cap: 2, type: 7, title: 'Schedule-aware repeat rules',
    need: 'The system knows which medicines can join a repeat service and for how long, by schedule, repeats left and script expiry.',
    why: 'Schedule 6 has no repeats and other repeats stop at six months; a service that ignores this breaks either the law or its promise.',
    principles: ['Get the basics right, every time', 'Repeats should just repeat'], status: 'New',
    statusNote: 'HSQ shows repeat requests as Live, but nothing schedule-aware for a standing service.',
    seen: [], enables: [P0, PX], evidence: ['wiki/sa-regulatory/prescription-requirements-repeats'] },
  { key: 's6-repeats', cap: 2, type: 3, reform: true, title: 'Repeats for chronic Schedule 6',
    need: 'Stable patients on long-term Schedule 6 medicine (ADHD treatment, for example) can receive repeats under safeguards, without a new script every month.',
    why: 'The law allows no Schedule 6 repeats and a 30-day maximum, so Zanele\'s family needs a new doctor\'s script every month.',
    principles: ['Repeats should just repeat'], status: 'New', seen: [], enables: [P0, PX],
    evidence: ['wiki/sa-regulatory/prescription-requirements-repeats', 'wiki/sa-regulatory/medicines-act-scheduling'] },
  { key: 'renewal-orchestration', cap: 2, type: 7, title: 'Proactive script renewal',
    need: 'Weeks before a script\'s last repeat, a renewal request goes to the prescriber automatically and is tracked until the new script is back.',
    why: 'So a script never lapses by surprise, and the customer isn\'t the one phoning a receptionist.',
    principles: ['Repeats should just repeat', 'Don\'t leave me in the dark'], status: 'Known gap',
    statusNote: 'HSQ: proactive renewal (provider-initiated, ~6 weeks ahead) is a Gap on every channel.',
    seen: ['HSQ', 'ECM'], enables: [PX, P5], concepts: ['Script Renew'], deps: ['repeat-rules'],
    evidence: ['wiki/sa-regulatory/prescription-requirements-repeats'] },
  { key: 'renewal-status', cap: 2, type: 5, title: 'Renewal status for customers',
    need: 'Customers can see where their renewal stands, and hear early, with a plan, if it won\'t arrive in time.',
    why: 'So an expiring script becomes a known date, not a missed dose.',
    principles: ['Don\'t leave me in the dark'], status: 'Known gap', statusNote: 'HSQ: proactive renewal Gap.',
    seen: ['HSQ'], enables: [PX], concepts: ['Script Renew'], deps: ['renewal-orchestration'] },
  { key: 'prescriber-link', cap: 2, type: 11, title: 'Prescriber renewal link',
    need: 'Doctors can receive renewal requests and send valid scripts back to Dis-Chem electronically.',
    why: 'Renewal can only be proactive if the doctor\'s side is quick; GP scripts reach stores by email or paper today.',
    principles: ['Many inputs, one controlled funnel'], status: 'Planned',
    statusNote: 'FUL s18: target state is verified email or a GP submission platform, all scripts to the Adherence Centre.',
    seen: ['FUL s18'], enables: [PX], deps: ['renewal-orchestration'] },
  { key: 'bridging-supply', cap: 2, type: 1, title: 'Bridging supply rules',
    need: 'A confirmed legal position on what a pharmacist may supply while a renewal is pending, by schedule.',
    why: 'The journey promises a plan when a renewal is late; we need to know what that plan can legally include.',
    principles: ['My pharmacist is my front door to care'], status: 'New',
    statusNote: 'Vault flags emergency-supply provisions as unverified (meta/open-questions.md).',
    seen: [], enables: [PX], evidence: ['wiki/sa-regulatory/prescription-requirements-repeats'] },

  // ---------------------------------------------------------------- 3 Pricing, funding and payment
  { key: 'pre-adjudication', cap: 3, type: 7, title: 'Scheme check before the notice',
    need: 'Every repeat is checked with the medical scheme before the customer is told what it costs.',
    why: 'So the price in the message is the price at the end, and declines surface at home rather than at the door.',
    principles: ['Give me all the variables upfront'], status: 'Known gap',
    statusNote: 'HSQ: prospective eligibility check Live in app, Gap on WhatsApp; nothing runs it ahead of a repeat.',
    seen: ['HSQ', 'ECM'], enables: [P1, PX], evidence: ['wiki/medical-schemes/realtime-claims-switching'] },
  { key: 'price-engine', cap: 3, type: 7, title: 'One medicine price engine',
    need: 'Every line (medicine price plus dispensing fee) is priced the same way in every store and channel.',
    why: 'Customers read store-to-store price differences on scheduled medicine as arbitrary, which costs trust even when the price is legal.',
    principles: ['Give me all the variables upfront'], status: 'Known gap',
    statusNote: 'HSQ: upfront cost estimate and price comparison are Gaps. ECM names Pricing & Cost Modelling.',
    seen: ['HSQ', 'ECM'], enables: [P1, P2], evidence: ['wiki/sa-regulatory/sep-dispensing-fee', 'wiki/dischem/pharmacy-complaints-pain-points'] },
  { key: 'itemised-cost', cap: 3, type: 5, title: 'Itemised household cost',
    need: 'The monthly notice shows each person\'s medicine, what each scheme covers, any shortfall and the total to pay.',
    why: 'Medicine is the one thing people buy blind; showing the numbers at home removes the surprise at the till.',
    principles: ['Give me all the variables upfront'], status: 'Known gap', statusNote: 'HSQ: upfront cost estimate Gap.',
    seen: ['HSQ', 'ECM'], enables: [P1], concepts: ['Real-Time Transparency'], deps: ['pre-adjudication', 'price-engine'] },
  { key: 'multi-funder', cap: 3, type: 7, title: 'Several schemes, one order',
    need: 'One household order can charge several medical schemes and put the remainder on one card.',
    why: 'A carer\'s household rarely shares one scheme, and multiple funders mean multiple orders today.',
    principles: ['Give me all the variables upfront'], status: 'Planned',
    statusNote: 'FUL s22: one submission across multiple funders in the target state (MLP no change). HSQ: split payment Planned.',
    seen: ['HSQ', 'ECM', 'FUL s22'], enables: [P0, P1], deps: ['pre-adjudication', 'household-profile'] },
  { key: 'saved-payment', cap: 3, type: 5, title: 'Saved payment and decline rule',
    need: 'Customers save a card and choose in advance what happens if a scheme declines a line: ask first, or pay and carry on.',
    why: 'So a decline becomes a choice already made, instead of a stalled order.',
    principles: ['Repeats should just repeat'], status: 'Planned', statusNote: 'HSQ: in-app payment Planned.',
    seen: ['HSQ'], enables: [P0, PX] },
  { key: 'decline-message', cap: 3, type: 5, title: 'Decline choices message',
    need: 'When a scheme declines a line, the customer is told what, why and their live options, and can settle it in one reply.',
    why: 'An exception can quietly cancel a chronic delivery today; this turns it into a decision.',
    principles: ['Don\'t leave me in the dark'], status: 'New', seen: [], enables: [PX], deps: ['pre-adjudication', 'saved-payment'],
    evidence: ['wiki/dischem/pharmacy-complaints-pain-points'] },
  { key: 'bank-partner', cap: 3, type: 11, title: 'Cash payment at a bank partner',
    need: 'A bank partner takes cash for a Dis-Chem order at its counter, and that payment releases the parcel.',
    why: 'Most customers pay cash; paying where they already bank removes a separate trip.',
    principles: ['Care extends beyond the counter'], status: 'New',
    statusNote: 'Design assumption in 09. Dis-Chem and Capitec already partner on rewards.',
    seen: [], enables: [P0, P4], evidence: ['sources/src-capitec-dischem-better-rewards-2025'] },
  { key: 'payment-release', cap: 3, type: 7, title: 'Payment switches on collection',
    need: 'A confirmed payment, wherever it is made, activates the customer\'s collection code.',
    why: 'So an unpaid parcel can wait safely in a locker and open only once it is paid for.',
    principles: ['Get the basics right, every time'], status: 'New', seen: [], enables: [P4], deps: ['bank-partner', 'handover-code'] },
  { key: 'commercial-model', cap: 3, type: 2, title: 'Repeat service commercial model',
    need: 'A decision on what the repeat service costs the customer: free basics, paid extras like dose sachets, and who pays for sync top-ups and delivery.',
    why: 'The journeys promise free basics and paid extras; pricing and the business case must be settled before launch.',
    principles: ['Give me all the variables upfront'], status: 'New', seen: [], enables: [P0, P5] },

  // ---------------------------------------------------------------- 4 Knowing and managing stock
  { key: 'live-stock', cap: 4, type: 7, title: 'Live stock visibility',
    need: 'Every store and the Adherence Centre know, in real time, what dispensary stock they hold, including part packs and stock on order.',
    why: 'So a customer is never promised a medicine the store doesn\'t have.',
    principles: ['Don\'t leave me in the dark', 'The system prioritises the work'], status: 'Known gap',
    statusNote: 'FUL s21: stock updates nightly and miscounts part packs; target is real-time, but the MLP is "no change". FUL s40 unlock.',
    seen: ['ECM', 'FUL s21', 'FUL s40'], enables: [P1, PX] },
  { key: 'reserve-for-repeats', cap: 4, type: 7, title: 'Stock held for predicted repeats',
    need: 'Predicted repeat orders reserve or trigger stock ahead of the order date.',
    why: 'If Dis-Chem knows a medicine is needed on the 28th, it should never be out of stock on the 28th.',
    principles: ['Repeats should just repeat', 'Fulfilment like a production line'], status: 'New',
    seen: [], enables: [P1, PX], deps: ['live-stock', 'refill-prediction'] },
  { key: 'stock-discipline', cap: 4, type: 9, title: 'Stock recorded as it moves',
    need: 'Stores record stock movements, part packs and returns accurately, as they happen.',
    why: 'Live visibility is only as good as what goes in, and today\'s counts miss part packs.',
    principles: ['Get the basics right, every time'], status: 'Known gap',
    statusNote: 'FUL s21 and s52: inaccurate stock data sets off a domino effect across the process.',
    seen: ['FUL s21', 'FUL s52'], enables: [P1, PX], deps: ['live-stock'] },
  { key: 'out-of-stock-choices', cap: 4, type: 5, title: 'Out-of-stock choices',
    need: 'If a line is out of stock, the customer gets a drafted plan (covered generic, split delivery or hold) and chooses in one reply.',
    why: 'So a stock-out costs a decision, not a wasted trip or a gap in treatment.',
    principles: ['Don\'t leave me in the dark'], status: 'Known gap',
    statusNote: 'FUL s20: out-of-stock comms by app, call or WhatsApp; MLP no change vs. current.',
    seen: ['FUL s20'], enables: [PX], deps: ['live-stock', 'split-delivery'] },

  // ---------------------------------------------------------------- 5 Dispensing and pharmacist care
  { key: 'brix-workflow', cap: 5, type: 7, title: 'One order workflow (BRiX)',
    need: 'One workflow carries each order from intake through checking, packing and handover, across the Adherence Centre, stores and delivery.',
    why: 'The Adherence Centre works across three dashboards today; one flow removes duplicate work and lets the system set the priorities.',
    principles: ['The system prioritises the work', 'Many inputs, one controlled funnel'], status: 'In flight',
    statusNote: 'BRiX launches early 2027 (programme update, 2026-10-04). FUL s21, s40.',
    seen: ['FUL s21', 'FUL s40'], enables: [P1, P3, P4], evidence: ['wiki/digital-transformation/dischem-scripting-tech-roadmap'] },
  { key: 'auto-processing', cap: 5, type: 7, title: 'Repeats prepare themselves',
    need: 'Eligible repeat orders are created and prepared automatically, without anyone re-keying them each month.',
    why: 'So staff time goes to the orders that need judgement.',
    principles: ['Fulfilment like a production line', 'Repeats should just repeat'], status: 'Planned',
    statusNote: 'FUL s17: eligible repeats auto-dispensed without PBQ review in the target state.',
    seen: ['FUL s17', 'FUL s40'], enables: [P1], deps: ['brix-workflow', 'refill-prediction', 'auto-refill-policy'] },
  { key: 'ai-checks', cap: 5, type: 6, title: 'AI check assistant',
    need: 'Software drafts the clinical checks for each order (interactions, allergies, doses, across the household) for the pharmacist to confirm or override.',
    why: 'The pharmacist spends their time judging rather than compiling, and every check is recorded.',
    principles: ['The counter is for care, not admin', 'Remove noise to protect flow'], status: 'Planned',
    statusNote: 'FUL s20: AI tools assist validation (overdose check). HSQ: pre-dispensing safety questionnaire Gap.',
    seen: ['ECM', 'FUL s20', 'HSQ'], enables: [P3], deps: ['brix-workflow'], evidence: ['wiki/digital-transformation/ai-in-pharmacy'] },
  { key: 'ai-regulation', cap: 5, type: 3, reform: true, title: 'Rules for AI-assisted checking',
    need: 'Clarity from the Pharmacy Council on how AI-drafted checks may support, but never replace, the pharmacist\'s sign-off.',
    why: 'Without it, the assistant risks being treated as the checker, and pharmacists won\'t trust or use it.',
    principles: ['Get the basics right, every time'], status: 'New', seen: [], enables: [P3],
    evidence: ['wiki/digital-transformation/ai-in-pharmacy', 'wiki/sa-regulatory/pharmacy-act-sapc-gpp'] },
  { key: 'signoff-record', cap: 5, type: 6, title: 'Named sign-off record',
    need: 'Each order records which checks ran and which pharmacist signed it off, in a form that can be shown to the customer.',
    why: 'The record makes the check provable, inside the business and to the customer.',
    principles: ['Get the basics right, every time'], status: 'Planned',
    statusNote: 'FUL s34: pharmacists review every order once, with input and validation tracked end-to-end.',
    seen: ['ECM', 'FUL s34'], enables: [P3], deps: ['brix-workflow'] },
  { key: 'named-check-status', cap: 5, type: 5, title: 'Checked-and-packed status',
    need: 'Customers get a status listing what was checked and the name of the pharmacist who signed it off, then a second when the parcel is sealed.',
    why: 'Customers treat dispensing errors as safety threats; seeing the check, with a name on it, replaces worry with evidence.',
    principles: ['Don\'t leave me in the dark', 'Get the basics right, every time'], status: 'New',
    statusNote: 'Not in any catalogue. HSQ has script status tracking (Live), but not the itemised, named version.',
    seen: [], enables: [P3], concepts: ['The Named Check'], deps: ['signoff-record'],
    evidence: ['wiki/dischem/dischem-social-sentiment-trust-journey'] },
  { key: 'naming-policy', cap: 5, type: 4, title: 'Naming the pharmacist',
    need: 'A policy that lets pharmacists\' names appear on customer statuses, agreed with HR and on safety.',
    why: 'The Named Check depends on it, and staff need to be comfortable before their names go on messages.',
    principles: ['My pharmacist is my front door to care'], status: 'New', seen: [], enables: [P3], concepts: ['The Named Check'] },
  { key: 'rowa', cap: 5, type: 6, title: 'Automated picking (ROWA)',
    need: 'A robot picks eligible stock for each order, and people prepare the items it can\'t handle.',
    why: 'Picking is the most manual step; automating it frees staff and cuts picking errors.',
    principles: ['Fulfilment like a production line', 'Separation & specialisation create focus'], status: 'In flight',
    statusNote: 'First ROWA goes in mid-2027 (programme update, 2026-10-04). FUL s21, s40.',
    seen: ['ECM', 'FUL s21', 'FUL s40'], enables: [P3], evidence: ['wiki/digital-transformation/pharmacy-automation-and-robotics'] },
  { key: 'pick-verification', cap: 5, type: 6, title: 'Pick verification',
    need: 'Every picked item is scanned or visually checked against the order before packing, with look-alikes flagged.',
    why: 'Short packs and wrong items are found at home today; this catches them in the building.',
    principles: ['Get the basics right, every time'], status: 'Planned', statusNote: 'FUL s17: scan to confirm the correct packaged medication.',
    seen: ['FUL s17'], enables: [P3], evidence: ['wiki/dispensing-practice/error-prevention-and-safety'] },
  { key: 'generic-consent', cap: 5, type: 9, title: 'Explained generic switch',
    need: 'When a generic replaces a usual brand, the switch is explained and the customer agrees before it is dispensed.',
    why: 'Customers read an unexplained generic as the wrong medicine, so substitution needs consent as well as a price.',
    principles: ['My pharmacist is my front door to care'], status: 'Planned',
    statusNote: 'HSQ: approved generic substitution shown at dispense Live in app. ECM: Medication Substitution & Cost Optimisation.',
    seen: ['HSQ', 'ECM'], enables: [PX], evidence: ['wiki/dischem/dischem-social-sentiment-trust-journey'] },
  { key: 'pharmacist-messaging', cap: 5, type: 5, title: 'Pharmacist in the thread',
    need: 'Customers can message a pharmacist about their medicine in the app or on WhatsApp, in the same thread as their order.',
    why: 'So a question gets a qualified answer without a trip to the counter.',
    principles: ['My pharmacist is my front door to care'], status: 'Known gap',
    statusNote: 'HSQ: two-way pharmacist messaging Gap on app, web and WhatsApp.',
    seen: ['HSQ', 'ECM'], enables: [P5, PX], deps: ['conversation-console', 'remote-pharmacists'] },
  { key: 'remote-pharmacists', cap: 5, type: 10, title: 'Remote pharmacist service',
    need: 'Pharmacists are rostered to answer customers\' medicine questions in the app and on WhatsApp, at the hours the service promises.',
    why: 'The repeat service promises a pharmacist in the thread; that needs people, hours and a response-time target.',
    principles: ['My pharmacist is my front door to care', 'The counter is for care, not admin'], status: 'Known gap',
    statusNote: 'HSQ: two-way pharmacist messaging Gap. ECM: Virtual Pharmacy Care.',
    seen: ['HSQ', 'ECM'], enables: [P5, PX] },
  { key: 'ac-capacity', cap: 5, type: 10, title: 'Adherence Centre capacity',
    need: 'The Adherence Centre has enough PBQs and pharmacists, on the right hours, for repeat volumes as they grow.',
    why: 'FUL estimates about 65-80 more PBQs to reach roughly 14,000 scripts a day, before household repeats add to it.',
    principles: ['Separation & specialisation create focus'], status: 'Planned', statusNote: 'FUL s43-45 staffing model.',
    seen: ['FUL s44'], enables: [P1, P3] },

  // ---------------------------------------------------------------- 6 Collection and delivery
  { key: 'open-order', cap: 6, type: 5, title: 'Open order window',
    need: 'Until the day before delivery, customers can add shop items (or OTC medicine on the locker route) to their repeat order.',
    why: 'So the delivery still does the double duty the store trip used to do.',
    principles: [], status: 'New', statusNote: 'Design assumption in 09 (punchlist item 9).',
    seen: [], enables: [P2], concepts: ['The Standing Order'], deps: ['one-parcel'] },
  { key: 'one-parcel', cap: 6, type: 7, title: 'One household parcel',
    need: 'All of a household\'s medicine and shop items are consolidated into one parcel and one delivery.',
    why: 'Separate parcels mean separate trips, fees and chances to go wrong.',
    principles: ['Fulfilment like a production line'], status: 'Planned',
    statusNote: 'FUL s17, s21: combined script and e-commerce orders in the target state. Roadmap: consolidation hub (PICCUP).',
    seen: ['FUL s17', 'FUL s21'], enables: [P2, P3, P4], deps: ['brix-workflow'], evidence: ['wiki/digital-transformation/dischem-scripting-tech-roadmap'] },
  { key: 'combined-pick', cap: 6, type: 9, title: 'Combined pick and pack',
    need: 'Front-shop and pharmacy staff follow one set process for picking shop items alongside medicine and holding them together.',
    why: 'Pick-and-pack roles are unclear between front shop and dispensary today, which delays combined orders.',
    principles: ['Separation & specialisation create focus'], status: 'Planned', statusNote: 'FUL s17.',
    seen: ['FUL s17'], enables: [P3], deps: ['one-parcel'] },
  { key: 'plan-changes', cap: 6, type: 5, title: 'Flexible delivery plans',
    need: 'Customers can move the day or window, or switch to collection, until the day before, in one reply.',
    why: 'Plans change; letting the parcel follow them avoids failed deliveries and wasted trips.',
    principles: [], status: 'New', seen: [], enables: [P3] },
  { key: 'tracking', cap: 6, type: 5, title: 'Live delivery tracking',
    need: 'Customers can watch their parcel move from the dispensary to their door or locker.',
    why: 'The worst failure today is "out for delivery, then nothing"; visible progress ends that.',
    principles: ['Don\'t leave me in the dark'], status: 'Planned', statusNote: 'FUL s19 driver orchestration; s40 unlock.',
    seen: ['FUL s19', 'FUL s40'], enables: [P4], evidence: ['wiki/dischem/pharmacy-complaints-pain-points'] },
  { key: 'handover-code', cap: 6, type: 7, title: 'Closed-loop handover code',
    need: 'Each parcel has a QR code with a backup PIN that works at the door, the locker and the store counter, and only a scan closes the order.',
    why: '"Delivered" then means in the customer\'s hands, not left at a gate.',
    principles: ['Get the basics right, every time', 'Don\'t leave me in the dark'], status: 'Planned',
    statusNote: 'Roadmap: driver proof of delivery (PICCUP). Locker and counter use of the same code is new.',
    seen: ['FUL s19'], enables: [P4, PX], evidence: ['wiki/digital-transformation/dischem-scripting-tech-roadmap'] },
  { key: 'failed-delivery', cap: 6, type: 7, title: 'Failed delivery re-planned',
    need: 'When a delivery fails, the parcel is re-planned with the customer: delivered tomorrow, or collected at a store on the same code.',
    why: 'So a missed delivery stays a short delay instead of a lost parcel.',
    principles: ['Don\'t leave me in the dark'], status: 'Known gap', statusNote: 'FUL s40: unified collections across store types.',
    seen: ['FUL s40'], enables: [PX], deps: ['handover-code', 'any-counter'] },
  { key: 'split-delivery', cap: 6, type: 7, title: 'Split delivery on stock-out',
    need: 'An order can be split so the rest arrives on time and a missing item follows on its own.',
    why: 'One missing medicine shouldn\'t hold up a whole household\'s supply.',
    principles: ['Don\'t leave me in the dark'], status: 'New', statusNote: 'Design assumption in 09 (punchlist item 9).',
    seen: [], enables: [PX], deps: ['one-parcel'] },
  { key: 'any-counter', cap: 6, type: 9, title: 'Collect any order at any counter',
    need: 'Any store counter can hand over any digital order, including a failed delivery, on the customer\'s code.',
    why: 'Collections differ by channel and store type today, so customers get sent from counter to counter.',
    principles: ['Get the basics right, every time'], status: 'Planned', statusNote: 'FUL s19 unified collections; s40 unlock.',
    seen: ['FUL s19', 'FUL s40'], enables: [PX] },
  { key: 'locker-network', cap: 6, type: 11, title: 'Near-home locker network',
    need: 'Lockers at partner sites near where customers live and travel, such as bank branches by taxi ranks.',
    why: 'Many cash customers have no Dis-Chem nearby and no deliverable street address.',
    principles: ['Care extends beyond the counter'], status: 'New', statusNote: 'Design assumption in 09.',
    seen: [], enables: [P0, P4], evidence: ['wiki/consumer-context/last-mile-addressing-logistics', 'wiki/concepts/remote-collection-points'] },
  { key: 'locker-integration', cap: 6, type: 7, title: 'Locker integration',
    need: 'Dis-Chem\'s systems load, monitor and release locker parcels, and know before the customer travels if a locker is down.',
    why: 'So nobody spends taxi fare on a closed door.',
    principles: ['Don\'t leave me in the dark'], status: 'New', seen: [], enables: [P4, PX], deps: ['locker-network', 'payment-release'] },
  { key: 'locker-scheduled', cap: 6, type: 3, reform: true, title: 'Scheduled medicine from lockers',
    need: 'Rules that allow scheduled medicine to be collected from an unattended locker, with the right pharmacist oversight.',
    why: 'Lockers only work for repeats if the medicines that matter can go in them.',
    principles: ['Proximity without exposure'], status: 'New', seen: [], enables: [P4],
    evidence: ['wiki/sa-regulatory/courier-online-pharmacy-rules', 'wiki/concepts/unmanned-collection-points'] },
  { key: 'courier-compliance', cap: 6, type: 9, title: 'Medicine courier compliance',
    need: 'Delivery and locker routes meet licensing, cold-chain and scheduled-medicine handling rules, and can pass a GPP audit.',
    why: 'Medicine in transit is still dispensed medicine, and one failure here is a safety and licence risk.',
    principles: ['Get the basics right, every time'], status: 'New', seen: [], enables: [P4],
    evidence: ['wiki/sa-regulatory/courier-online-pharmacy-rules', 'wiki/dispensing-practice/inventory-coldchain-controlled'] },
  { key: 'contents-check', cap: 6, type: 5, title: 'Contents check with photo help',
    need: 'After handover, customers get a list of what should be in the parcel and can send a photo to trigger an immediate call-back.',
    why: 'A short pack is caught while the parcel is still in front of them, not days later.',
    principles: ['Get the basics right, every time', 'Never turn your back on the customer'], status: 'New',
    statusNote: 'Design assumption in 09. Related HSQ Gap: context-carrying handoff.',
    seen: [], enables: [P4], deps: ['call-me-back'] },
  { key: 'delivery-promise', cap: 6, type: 2, title: 'Delivery promise standard',
    need: 'A decision on the delivery windows Dis-Chem promises for repeats, and what happens when a promise is missed.',
    why: 'Customers distrust over-precise promises and judge the service on whether the window held.',
    principles: ['Don\'t leave me in the dark'], status: 'Known gap',
    statusNote: 'FUL s20: follow-up when a promise is missed is TBD. FUL s61: slots calibrated to dispensary times.',
    seen: ['FUL s20', 'FUL s61'], enables: [P1, P4], evidence: ['wiki/dischem/store-of-the-future-customer-voice'] },
  { key: 'retail-rules', cap: 6, type: 2, title: 'What rides with medicine',
    need: 'A decision on what can join a medicine delivery (the whole store or a subset, any fee or minimum) and on the medicine-only locker rule.',
    why: 'Retail on the delivery is commercial upside, but it changes picking, parcel size and the locker route.',
    principles: [], status: 'New', seen: [], enables: [P2] },
  { key: 'cash-vp', cap: 6, type: 1, title: 'Cash customer proposition test',
    need: 'Evidence that cash customers will use a WhatsApp repeat service with a bank locker and pay-at-counter collection.',
    why: 'The cash journey rests on untested assumptions about trust, cost and travel.',
    principles: ['Care extends beyond the counter'], status: 'New', seen: [], enables: [P0, P4] },

  // ---------------------------------------------------------------- 7 Adherence and refills
  { key: 'signup', cap: 7, type: 5, title: 'Repeat service sign-up',
    need: 'Customers join a standing repeat service in the app or on WhatsApp in a few minutes, and see everything read back before they confirm.',
    why: 'Setting it up once is what lets every later month run without effort.',
    principles: ['Repeats should just repeat'], status: 'New', statusNote: 'HSQ has repeat requests (Live), not a standing service.',
    seen: [], enables: [P0], concepts: ['Auto-Refill'], deps: ['household-profile', 'preferences', 'repeat-rules'] },
  { key: 'refill-prediction', cap: 7, type: 7, title: 'Refill prediction',
    need: 'The system predicts each person\'s run-out date from their dispensing history.',
    why: 'Knowing the date is what lets the order prepare itself a week early.',
    principles: ['Repeats should just repeat'], status: 'Planned',
    statusNote: 'FUL s17: refill notices 3-6 days ahead. HSQ: refill reminder Live in app, Gap on WhatsApp.',
    seen: ['HSQ', 'ECM', 'FUL s17'], enables: [P1], evidence: ['wiki/digital-transformation/adherence-tech-and-digital-therapeutics'] },
  { key: 'script-sync', cap: 7, type: 7, title: 'Script Sync engine',
    need: 'The system works out how to bring a household\'s medicines onto one date, knows which ones can\'t move, and prices the one-off top-up.',
    why: 'One date means one notice, one parcel and one trip, instead of a medicine calendar kept in someone\'s head.',
    principles: ['Repeats should just repeat', 'Give me all the variables upfront'], status: 'New',
    seen: [], enables: [P0], concepts: ['Script Sync'], deps: ['refill-prediction', 'repeat-rules', 'price-engine'] },
  { key: 'sync-scheme-rules', cap: 7, type: 1, title: 'Scheme rules for part-fills',
    need: 'Confirmed medical scheme rules on early refills and part-fills used to sync cycles.',
    why: 'Sync relies on one-off top-ups; if schemes won\'t pay for them, the customer pays or sync doesn\'t work.',
    principles: ['Give me all the variables upfront'], status: 'New', statusNote: 'Unsourced in the vault (punchlist).',
    seen: [], enables: [P0], concepts: ['Script Sync'] },
  { key: 'auto-refill-policy', cap: 7, type: 4, title: 'Auto-refill eligibility policy',
    need: 'Dis-Chem defines which medicines and customers may run on a standing order without monthly confirmation.',
    why: 'Automation needs a clear line: a stable blood-pressure tablet can repeat itself, a newly started or high-risk medicine may not.',
    principles: ['Repeats should just repeat'], status: 'Planned',
    statusNote: 'FUL s17: "eligible repeat orders (e.g., long-term)"; eligibility not yet defined.',
    seen: ['FUL s17'], enables: [P1], concepts: ['Auto-Refill'] },
  { key: 'monthly-notice', cap: 7, type: 5, title: 'Monthly repeat notice',
    need: 'A week before run-out, one message tells the household what is being prepared, when it arrives and what it costs.',
    why: 'The chore of re-ordering disappears; the customer only acts if something needs to change.',
    principles: ['Repeats should just repeat', 'Don\'t leave me in the dark'], status: 'Planned',
    statusNote: 'FUL s17: refill notification 3-6 days ahead. HSQ: status alerts Live.',
    seen: ['HSQ', 'FUL s17'], enables: [P1], concepts: ['Auto-Refill'], deps: ['refill-prediction', 'itemised-cost'] },
  { key: 'standing-controls', cap: 7, type: 5, title: 'Standing order controls',
    need: 'Customers can amend, swap a line, pause or cancel in one tap or one reply, and the order carries on if they say nothing.',
    why: 'People let a service run on its own only when they know they can stop it.',
    principles: ['Repeats should just repeat'], status: 'Known gap', statusNote: 'HSQ: pause/resume a medication subscription Gap.',
    seen: ['HSQ'], enables: [P1] },
  { key: 'autorefill-validation', cap: 7, type: 1, title: 'Validate Auto-Refill',
    need: 'Evidence that customers trust medicine that orders and charges itself, and what controls they need to feel safe.',
    why: 'Auto-Refill is the heart of the repeat journey; if people won\'t let it run, nothing downstream matters.',
    principles: ['Repeats should just repeat'], status: 'New', seen: [], enables: [P1], concepts: ['Auto-Refill'] },
  { key: 'repeat-vp', cap: 7, type: 1, title: 'Repeat service value proposition',
    need: 'Research on what would make customers move their chronic medicine to Dis-Chem\'s repeat service and stay.',
    why: 'The service competes with medical scheme courier pharmacies and other retailers; we need to know which promises win.',
    principles: ['Repeats should just repeat'], status: 'New', seen: [], enables: [P0, P1],
    evidence: ['wiki/medical-schemes/courier-chronic-pharmacy-models'] },
  { key: 'dose-packs', cap: 7, type: 9, title: 'Dose-pack production',
    need: 'The dispensary can produce a month of per-dose sachets for a household, labelled by person, time and food.',
    why: 'Pre-sorted doses make medicine hard to take wrong, especially for older people on many medicines.',
    principles: ['Get the basics right, every time', 'Care extends beyond the counter'], status: 'Known gap',
    statusNote: 'HSQ: adherence packaging subscription Gap. ECM: Automated Dispensing Enablement.',
    seen: ['HSQ', 'ECM'], enables: [P3, P5], concepts: ['Made-for-Me Medicine'], evidence: ['wiki/dispensing-practice/adherence-packaging'] },
  { key: 'dose-pack-vp', cap: 7, type: 1, title: 'Dose-pack proposition',
    need: 'Evidence on who would pay for dose sachets, and at what price.',
    why: 'Sachets are the paid end of Made-for-Me Medicine; the price has to work for families and for Dis-Chem.',
    principles: ['Care extends beyond the counter'], status: 'New', seen: [], enables: [P0, P5], concepts: ['Made-for-Me Medicine'] },
  { key: 'reminders', cap: 7, type: 5, title: 'Patient-controlled reminders',
    need: 'Reminders go to the person who takes the medicine (children\'s to the carer), in their language, and stop when that person says so.',
    why: 'Reminders help when they respect the person, and feel like harassment when they don\'t.',
    principles: ['Care extends beyond the counter'], status: 'Known gap',
    statusNote: 'HSQ: check-in reminders Gap. ECM: Automated Engagement & Nudge System.',
    seen: ['HSQ', 'ECM'], enables: [P5], deps: ['preferences', 'contact-policy'] },
  { key: 'contact-policy', cap: 7, type: 4, title: 'Contact and opt-out policy',
    need: 'A policy that limits how often Dis-Chem contacts a customer and makes any opt-out apply across every channel.',
    why: 'Help turns into harassment when messages keep coming after someone has said stop.',
    principles: ['Get the basics right, every time'], status: 'Known gap', statusNote: 'HSQ: contact preference settings Gap.',
    seen: ['HSQ'], enables: [P1, P5], evidence: ['wiki/dischem/dischem-social-sentiment-trust-journey'] },
  { key: 'ccmdd-link', cap: 7, type: 11, reform: true, title: 'Government programme link',
    need: 'A data link with the government chronic medicine programme (CCMDD), so Dis-Chem knows a family member\'s programme collection date.',
    why: 'Cash households often mix programme and retail medicine; seeing both dates lets one service remember everything.',
    principles: ['Repeats should just repeat'], status: 'New', seen: [], enables: [P0, P1],
    evidence: ['wiki/medical-schemes/courier-chronic-pharmacy-models'] },
  { key: 'medicine-cabinet', cap: 7, type: 5, title: 'Household medicine cabinet',
    need: 'Every medicine the household takes is listed with what it\'s for, how to take it and its side effects, in the app and in the chat.',
    why: 'The answer to "how do I take this?" is there whenever the question comes up.',
    principles: ['Care extends beyond the counter'], status: 'Known gap',
    statusNote: 'HSQ: medication list Live in app, Gap on WhatsApp; content tied to an active script Gap.',
    seen: ['HSQ'], enables: [P5], concepts: ['Household Medicine Cabinet'], deps: ['instruction-library', 'household-profile'] },

  // ---------------------------------------------------------------- 8 Communicating with customers
  { key: 'instruction-library', cap: 8, type: 8, title: 'Usage instruction library',
    need: 'Every medicine\'s instructions are written once in plain language, checked by pharmacists, and stored for reuse.',
    why: 'Labels, sachets, fridge sheets, the app and WhatsApp can then all say the same thing.',
    principles: ['Get the basics right, every time', 'Care extends beyond the counter'], status: 'Known gap',
    statusNote: 'HSQ: content tied to an active script Gap ("printed leaflet only today"). ECM: Patient Education.',
    seen: ['HSQ', 'ECM'], enables: [P5], evidence: ['wiki/dispensing-practice/counselling-and-health-literacy'] },
  { key: 'label-design-system', cap: 8, type: 8, title: 'Label design system',
    need: 'One visual language (icons for time of day and food, layout, type size) used on labels, sachets, sheets and screens.',
    why: 'Icons speak before words do, for people with low literacy or poor eyesight.',
    principles: ['Get the basics right, every time'], status: 'New', seen: [], enables: [P5], concepts: ['Made-for-Me Medicine'],
    evidence: ['wiki/dispensing-practice/counselling-and-health-literacy'] },
  { key: 'translations', cap: 8, type: 8, title: 'Instructions in SA languages',
    need: 'Medicine instructions are translated into the main South African languages and clinically checked.',
    why: 'An instruction the patient can\'t read is no instruction at all.',
    principles: ['Care extends beyond the counter'], status: 'Known gap', statusNote: 'HSQ: language preference Gap.',
    seen: ['HSQ'], enables: [P0, P5], deps: ['instruction-library'] },
  { key: 'message-library', cap: 8, type: 8, title: 'Service message library',
    need: 'A tested set of service messages (notices, statuses, exceptions) in plain language, in each supported language, with one tone of voice.',
    why: 'Every channel and team then tells customers the same thing, the same way.',
    principles: ['Don\'t leave me in the dark'], status: 'New', seen: [], enables: [P1, P3, P4, PX] },
  { key: 'label-printing', cap: 8, type: 6, title: 'Per-person label printing',
    need: 'Dispensary printers produce iconised labels and fridge sheets in each person\'s language.',
    why: 'The design system only reaches the kitchen table if the dispensary can print it.',
    principles: ['Get the basics right, every time'], status: 'New', seen: [], enables: [P5],
    deps: ['label-design-system', 'translations'], evidence: ['wiki/digital-transformation/dischem-scripting-tech-roadmap'] },
  { key: 'labelling-rules', cap: 8, type: 1, title: 'Labelling rules check',
    need: 'Confirmed rules on what a dispensing label must carry, and whether icons and translated text may be added.',
    why: 'The design system has to sit inside the law before it goes on a single pack.',
    principles: ['Get the basics right, every time'], status: 'New', seen: [], enables: [P5],
    evidence: ['wiki/dispensing-practice/dispensing-process-steps'] },
  { key: 'whatsapp-platform', cap: 8, type: 7, title: 'WhatsApp service platform',
    need: 'WhatsApp can run the whole repeat service: sign-up, notices, statuses, payments, chat ordering and hand-off to a person.',
    why: 'WhatsApp is the channel most customers already use and can afford.',
    principles: ['Care extends beyond the counter'], status: 'Known gap',
    statusNote: 'HSQ: most medicine capabilities are Gap on WhatsApp. ECM names WhatsApp as the primary SA messaging channel.',
    seen: ['HSQ', 'ECM'], enables: [P0, P1, P2, P4, P5, PX], evidence: ['wiki/consumer-context/digital-access-and-whatsapp'] },
  { key: 'chat-ordering', cap: 8, type: 5, title: 'Chat ordering on WhatsApp',
    need: 'Customers add items in the chat by number or free text, answer a clarifying question and see priced options.',
    why: 'So the cash customer gets the same "add to my order" as the app user, on the phone they own.',
    principles: ['Give me all the variables upfront'], status: 'New', seen: [], enables: [P2], deps: ['whatsapp-platform', 'price-engine'] },
  { key: 'order-status', cap: 8, type: 5, title: 'Status at every stage',
    need: 'Customers are told at every stage of an order, without asking.',
    why: 'Silence reads as failure; a status that arrives unprompted keeps trust intact.',
    principles: ['Don\'t leave me in the dark'], status: 'Planned',
    statusNote: 'FUL s20: one-way comms at each stage; s40 unlock real-time notifications. HSQ: status alerts Live.',
    seen: ['HSQ', 'FUL s20', 'FUL s40'], enables: [P3, P4], deps: ['brix-workflow', 'message-library'] },
  { key: 'call-me-back', cap: 8, type: 5, title: 'Call me back',
    need: 'One reply asks for a call, and a person phones back in the customer\'s language.',
    why: 'When something breaks, people want a person, not more typing.',
    principles: ['Never turn your back on the customer'], status: 'Known gap', statusNote: 'HSQ: context-carrying handoff Gap.',
    seen: ['HSQ'], enables: [P1, P4, PX], deps: ['conversation-console', 'callback-team'] },
  { key: 'conversation-console', cap: 8, type: 6, title: 'Conversation console',
    need: 'Pharmacists and agents answer messages and call-backs with the household, the order and its history in front of them.',
    why: 'So one conversation runs to resolution and nobody starts over.',
    principles: ['Never turn your back on the customer', 'Remove noise to protect flow'], status: 'Known gap',
    statusNote: 'HSQ: context-carrying handoff Gap. ECM: Contact centre.',
    seen: ['HSQ', 'ECM'], enables: [P5, PX], deps: ['one-customer-record'] },
  { key: 'callback-team', cap: 8, type: 10, title: 'Multilingual call-back team',
    need: 'Enough staff who speak customers\' languages to return calls quickly when something breaks.',
    why: 'A call-back promise is only as good as the people who make the calls.',
    principles: ['Never turn your back on the customer'], status: 'New', seen: [], enables: [PX] },
  { key: 'exception-owner', cap: 8, type: 9, title: 'One owner per problem',
    need: 'Every problem with an order has one named owner until it is resolved, and the order keeps its place.',
    why: 'Problems die between teams today; one owner means one person accountable for the fix.',
    principles: ['Never turn your back on the customer', 'The system prioritises the work'], status: 'Planned',
    statusNote: 'Roadmap: Virtual Manager (SLA oversight). FUL s20: ownership of missed promises TBD.',
    seen: ['FUL s20'], enables: [PX], evidence: ['wiki/digital-transformation/dischem-scripting-tech-roadmap'] },
];

module.exports = { CAPS, TYPES, ITEMS };
